#Taylor Miller
#21-4-22
#Makefile for hands-on final cs3560
output: main.o
	g++ main.o -o count
main.o: main.cpp
	g++ -c main.cpp
clean:
	rm -r *.o count
check:
	cppcheck main.cpp 2> err.txt 
	valgrind --leak-check=full --show-leak-kinds=all ./count